import assert from "node:assert/strict";
import fs from "node:fs";
import { createGrid, deformGrid, deformPoint } from "../src/mesh/grid.js";
import { FACE_LAYOUTS, SOURCE_DIMENSIONS, blendNormalizedRect } from "../src/mesh/layout.js";
import { sampleTransition } from "../src/mesh/transition.js";

const neutral = { source: "stand", expression: "neutral", transitionMotion: "face_blend", pose: { x: 0, y: 0, rotation: 0, scale: 1 } };
const happy = { source: "stand", expression: "happy", transitionMotion: "face_blend", pose: { x: 0, y: -3, rotation: 0, scale: 1.02 } };
const excited = { source: "jump", expression: "excited", transitionMotion: "jump_settle", pose: { x: 0, y: -10, rotation: 0, scale: 1.03 } };
const start = sampleTransition(neutral, excited, 0); const mid = sampleTransition(neutral, excited, 0.5); const end = sampleTransition(neutral, excited, 1);
assert.equal(start.sourceMix, 0, "transition must start on the source texture");
assert.ok(mid.sourceMix > 0.35 && mid.sourceMix < 0.65, "mid-transition must hand off textures on one shared mesh");
assert.equal(end.sourceMix, 1, "transition must finish on the target texture");
assert.ok(mid.warp.armLift > 0.15, "neutral -> excited must visibly lift side/arm regions in intermediate frames");
assert.ok(mid.warp.scalePulse > 0.02, "excited transition must include a body impulse, not a flat fade");
assert.ok(Math.abs(end.warp.armLift) < 1e-8, "target pose must not retain transition-only arm deformation");
const sameSource = sampleTransition(neutral, happy, 0.5); assert.equal(sameSource.sameSource, true); assert.equal(sameSource.sourceMix, 0, "same-source emotions must never cross-fade the full character texture");
let previousMix = -1; let previousLift = 0;
for (let i = 0; i <= 40; i += 1) { const sample = sampleTransition(neutral, excited, i / 40); assert.ok(Number.isFinite(sample.sourceMix)); assert.ok(sample.sourceMix + 1e-8 >= previousMix, "texture handoff must be monotonic"); assert.ok(Math.abs(sample.warp.armLift - previousLift) < 0.06, "arm in-between curve must not jump between frames"); previousMix = sample.sourceMix; previousLift = sample.warp.armLift; }
const armBase = [-0.72, 0.22]; const armMid = deformPoint(armBase[0], armBase[1], {}, {}, mid.warp); const faceBase = [0, -0.28]; const faceMid = deformPoint(faceBase[0], faceBase[1], {}, {}, mid.warp);
assert.ok(armMid[1] < armBase[1] - 0.08, "arm region must move upward at the in-between pose"); assert.ok(Math.abs(faceMid[0] - faceBase[0]) < 0.04, "arm transition must not drag the face sideways");
const grid = createGrid(24, 28); const deformed = deformGrid(grid.positions, {}, {}, null, mid.warp); assert.equal(deformed.length, grid.positions.length); for (const value of deformed) assert.ok(Number.isFinite(value), "deformed mesh may not contain NaN/Infinity");
function sourceBoxFromCentered(rect, source) { const [w, h] = SOURCE_DIMENSIONS[source]; return [w / 2 + rect[0], h / 2 + rect[1], w / 2 + rect[0] + rect[2], h / 2 + rect[1] + rect[3]]; }
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.stand.leftEye, "stand"), [90, 103, 117, 123], "left eye must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.stand.rightEye, "stand"), [145, 103, 172, 123], "right eye must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.stand.mouth, "stand"), [112, 116, 145, 141], "mouth must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.peace.rightEye, "peace"), [147, 103, 174, 123], "peace wink eye must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.peace.mouth, "peace"), [110, 115, 142, 145], "peace mouth must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.uruuru.leftEye, "uruuru"), [78, 92, 119, 137], "uruuru left eye must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.uruuru.rightEye, "uruuru"), [151, 92, 192, 137], "uruuru right eye must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.uruuru.mouth, "uruuru"), [118, 120, 149, 141], "uruuru mouth must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.haku.leftEye, "haku"), [70, 96, 104, 131], "haku left eye must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.haku.rightEye, "haku"), [122, 96, 154, 131], "haku right eye must match the source crop manifest");
assert.deepEqual(sourceBoxFromCentered(FACE_LAYOUTS.jump.mouth, "jump"), [126, 140, 170, 180], "jump mouth must match the wide-mouth source crop manifest");
const blendedMouth = blendNormalizedRect(FACE_LAYOUTS.stand.mouth, SOURCE_DIMENSIONS.stand, FACE_LAYOUTS.jump.mouth, SOURCE_DIMENSIONS.jump, 0.5); assert.ok(blendedMouth?.every(Number.isFinite), "face overlay layout interpolation must stay finite"); assert.ok(blendedMouth[2] > 0 && blendedMouth[3] > 0, "blended face overlay must keep a positive size");
const presetMatrix = { neutral: { source: "stand", transitionMotion: "face_blend" }, happy: { source: "stand", transitionMotion: "face_blend" }, excited: { source: "jump", transitionMotion: "jump_settle" }, teasing: { source: "peace", transitionMotion: "limb_blend" }, pleading: { source: "uruuru", transitionMotion: "limb_blend" }, relaxed: { source: "gorogoro", transitionMotion: "lay_transition" }, sick: { source: "haku", transitionMotion: "sick_transition" }, angry: { source: "stand", transitionMotion: "face_blend" }, annoyed: { source: "stand", transitionMotion: "face_blend" }, sad: { source: "uruuru", transitionMotion: "face_blend" }, surprised: { source: "haku", transitionMotion: "quick_react" }, embarrassed: { source: "stand", transitionMotion: "face_blend" }, scared: { source: "haku", transitionMotion: "quick_react" }, smug: { source: "peace", transitionMotion: "limb_blend" }, confused: { source: "stand", transitionMotion: "face_blend" }, love: { source: "jump", transitionMotion: "jump_settle" } };
for (const [fromName, fromPreset] of Object.entries(presetMatrix)) { for (const [toName, toPreset] of Object.entries(presetMatrix)) { let lastMix = -1; for (let frame = 0; frame <= 60; frame += 1) { const sample = sampleTransition(fromPreset, toPreset, frame / 60); assert.ok(Number.isFinite(sample.progress), `${fromName}->${toName}: progress must be finite`); assert.ok(Number.isFinite(sample.sourceMix), `${fromName}->${toName}: source mix must be finite`); assert.ok(sample.sourceMix + 1e-9 >= lastMix, `${fromName}->${toName}: source mix must be monotonic`); for (const value of Object.values(sample.warp)) assert.ok(Number.isFinite(value), `${fromName}->${toName}: warp values must be finite`); lastMix = sample.sourceMix; } const first = sampleTransition(fromPreset, toPreset, 0); const last = sampleTransition(fromPreset, toPreset, 1); assert.equal(first.sourceMix, 0, `${fromName}->${toName}: must start on source`); if (fromPreset.source === toPreset.source) assert.equal(last.sourceMix, 0, `${fromName}->${toName}: same-source must not texture-fade`); else assert.equal(last.sourceMix, 1, `${fromName}->${toName}: must finish on target texture`); } }
const rendererSource = fs.readFileSync(new URL("../src/mesh/renderer.js", import.meta.url), "utf8"); assert.match(rendererSource, /UNPACK_FLIP_Y_WEBGL, false/, "DOM image textures must not be vertically flipped"); assert.doesNotMatch(rendererSource, /UNPACK_FLIP_Y_WEBGL, true/, "vertical texture flip reintroduces the upside-down avatar regression"); assert.match(rendererSource, /drawMeshBlend/, "source-changing transitions must use shared-mesh texture morphing");
const controllerSource = ["../src/mesh/controller.js", "../src/mesh/controller-state.js", "../src/mesh/controller-render.js"].map((path) => fs.readFileSync(new URL(path, import.meta.url), "utf8")).join("\n"); assert.match(controllerSource, /renderer\.drawMeshBlend/, "transition renderer must use one shared mesh"); assert.doesNotMatch(controllerSource, /renderEntity\(this\.transition\.from/, "full-character from/to alpha cross-fade path must stay removed"); assert.match(controllerSource, /emotionStartedAt = finished\.start/, "one-shot target motion age must continue through transition completion");
console.log("mesh visual regression test passed");
